name: Dockerhub Description

on:
  workflow_call:
    inputs:
      dockerhub-username:
        type: string
        required: true
        description: The hub.docker.com username under which the image's description should be updated.
    secrets:
      dockerhub-token:
        description: The token used to authenticate with hub.docker.com.
        required: true
    
jobs:
  dockerhub-description:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}

      - name: Update Repo Description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ inputs.dockerhub-username }}
          password: ${{ secrets.dockerhub-token }}
          repository: ${{ inputs.dockerhub-username }}/${{ github.event.repository.name }}
          short-description: ${{ github.event.repository.description }}
